langauge: node_js
dist: focal
services:
  - docker

jobs:
  include:
    - stage: test
      script:
      - cd ./api
      - npm run test
    - script:
      - cd ./client
      - npm run test -- --watchAll=false
    - stage: build
      if: branch = master
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/ense701-seer-server api
      - docker images
      - docker push $DOCKER_USERNAME/ense701-seer-server
    - script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/ense701-seer-client client
      - docker images
      - docker push $DOCKER_USERNAME/ense701-seer-client
    